apiVersion: v1
kind: Service
metadata:
  namespace: home-assistant
  name: matter-server-service
spec:
  selector:
    app: matter-server
  type: ClusterIP
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 5580
