apiVersion: v1
kind: Service
metadata:
  namespace: iperf3-server
  name: iperf3-server-service
spec:
  selector:
    app: iperf3-server
  type: ClusterIP
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 5201
