---
apiVersion: v1
kind: Namespace
metadata:
  name: iperf3-server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: iperf3-server
  name: iperf3-server-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iperf3-server
  template:
    metadata:
      labels:
        app: iperf3-server
    spec:
      containers:
        - name: iperf3-server
          image: leodotcloud/swiss-army-knife:latest
          ports:
            - containerPort: 5201
      hostNetwork: true
---
apiVersion: v1
kind: Service
metadata:
  namespace: iperf3-server
  name: iperf3-server-service
spec:
  selector:
    app: iperf3-server
  type: ClusterIP
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 5201
