---
apiVersion: v1
kind: Namespace
metadata:
  name: home-assistant
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: home-assistant
  name: home-assistant
  labels:
    app: home-assistant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: home-assistant
  template:
    metadata:
      labels:
        app: home-assistant
    spec:
      containers:
      - name: bluez
        image: ghcr.io/mysticrenji/bluez-service:v1.1.0
        securityContext:
          privileged: true
      - name: home-assistant
        image: ghcr.io/home-assistant/home-assistant:2024.9.1
        # image: ghcr.io/home-assistant/home-assistant:2024.4.3
        # image: ghcr.io/home-assistant/home-assistant:stable
        # imagePullPolicy: Always
        ports:
        - containerPort: 8123
        volumeMounts:
        - mountPath: /config
          name: ha-config        
        - mountPath: /run/dbus
          name: d-bus
          readOnly: true
        #- mountPath: /dev/video0
        #  name: cam
        securityContext:
          privileged: true
          capabilities:
            add:
              - NET_ADMIN
              - NET_RAW
              - SYS_ADMIN
      hostNetwork: true
      volumes:
      - name: ha-config
        hostPath:
          path: /root/cognifog/iot-edge-gw/ha-config
      #  hostPath:
      #    path: /tmp/home-assistant
      #    type: DirectoryOrCreate
      - name: d-bus
        hostPath:
          path: /run/dbus
      #- name: cam
      #  hostPath:
      #    path: /dev/video0