apiVersion: v1
kind: Service
metadata:
  namespace: iperf3-client
  name: iperf3-client-service
spec:
  selector:
    app: iperf3-client
  type: ClusterIP
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 5201
